
GET http://localhost:8080/lightstatus

###
POST  http://localhost:8080/prompt 
Content-Type: application/json

{
    "prompt": "Why might member with id 12345 be calling us?"
}

###
POST  http://localhost:8080/predictReason 
Content-Type: application/json

{
    "memberid": "12345"
}
###
GET http://localhost:8080/findbyid?param=123