
GET http://localhost:8951/lightstatus

###
POST  http://localhost:8951/prompt 
Content-Type: application/json

{
    "prompt": "Why might member with id 12345 be calling us?"
}

###
POST  http://localhost:8951/predictReason 
Content-Type: application/json

{
    "patientId": "124027968",
    "searchInputMetaData" : {
        "correlationId": "test1234"
    }
}
###

POST http://localhost:8951/conversation
Content-Type: application/json

{
    "id": "924f1ed0-daf0-453f-bc89f5237f3fefe6e",
    "patientId": "130697362",
    "correlationId": "skim62_test",
    "messages": [
        {
            "message": "Why?",
            "role": "USER",
            "time": "2023-10-01T12:00:00Z"
        }
    ]
}

###
GET http://localhost:8951/conversation

###
GET http://localhost:8951/conversation/cec7d4eb-76c2-4b15-ab86-67367ded907d

###
DELETE http://localhost:8951/conversation/cec7d4eb-76c2-4b15-ab86-67367ded907d
