AZURE_CLIENT_KEY: 
CLIENT_ENDPOINT: 
MODEL_ID:
AZURE_CLIENT_ID:
AZURE_TENANT_ID:
AZURE_CLIENT_SECRET:
AZURE_PROJECT_ID:
AZURE_COSMOS_URI:
AZURE_COSMOS_KEY:
AZURE_COSMOS_DATABASE:

spring:
  config:
    import: application-local.yml