AZURE_CLIENT_KEY: 
CLIENT_ENDPOINT: 
MODEL_ID:
AZURE_CLIENT_ID:
AZURE_TENANT_ID:
AZURE_CLIENT_SECRET:
AZURE_PROJECT_ID:
AZURE_COSMOS_CONN_STR:
AZURE_COSMOS_COLLECTION:
AZURE_COSMOS_DATABASE:
DEPLOYMENT_NAME: 
USE_OPENAPI_PLUGIN:
TEST_OPENAPI_SERVER_URL:

spring:
  config:
    import: application-local.yml  