AZURE_CLIENT_KEY: 
CLIENT_ENDPOINT: 
MODEL_ID:
AZURE_CLIENT_ID:
AZURE_TENANT_ID:
AZURE_CLIENT_SECRET:
AZURE_PROJECT_ID:
AZURE_COSMOS_CONN_STR: 
AZURE_COSMOS_COLLECTION:
AZURE_COSMOS_DATABASE:
#Leave blank for in memory 
mongoServiceName: 
#Uncomment below to use MongoDB
#mongoServiceName: mongoDatabaseService

spring:
  config:
    import: application-local.yml