AZURE_CLIENT_KEY: 
CLIENT_ENDPOINT: 
MODEL_ID:
AZURE_CLIENT_ID:
AZURE_TENANT_ID:
AZURE_CLIENT_SECRET:
AZURE_PROJECT_ID:

HemiAccessTokenEndpoint:
HemiPrescriptionSearchEndpoint:
HemiOrderDetailsEndpoint:
HemiAccessTokenRequest:
HemiAccessACQTokenRequest:

spring:
  config:
    import: application-local.yml