apiVersion: v1
kind: Service
metadata:
  name: SERVICE_NAME-dep
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  ports:
    - port: 8951
  selector:
    app: SERVICE_NAME-dep