version: '3.8'

services:
  app:
    image: mcr.microsoft.com/devcontainers/java:1-17-bullseye
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    network_mode: service:db
    
  db:
    image: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example