server:
  port: 8952

StargateAccessNavTokenEndpoint:
StargateAccessNavTokenRequest:
HemiAccessTokenEndpoint:
HemiAccessACQTokenRequest:
SetLocalEnvFlag: true
# For prod use setLocalEnvFlag: false

prop:
  include-inactive-patients: Y
  include-expired-prescriptions: Y
  include-discontinued-prescriptions: Y
  include-refillable-prescriptions: Y
  include-renewable-prescriptions: Y
  include-open-order-prescriptions: Y
  include-duplicate-gpi: Y

webclient:
  connection:
    timeout: 60000
  read:
    timeout: 60000
  write:
    timeout: 60000

httpclient:
    max-connections: 1000
    max-idle-time: 360000
    max-life-time: 360000
    pending-acq-timeout: 60000
    evict-in-background: 120000

---
 
spring:
  config:
    activate:
      on-profile:
      - test
  sleuth: 
    enabled: true
  application:
      name:
  cloud: 
    azure:
      keyvault:
        secret:
          property-sources[0]:
            credential:
              client-id: CLIENTID
              client-secret: CLIENTSECRET
            endpoint: https://acq-test-us-c-keyvault.vault.azure.net/
            profile:
              tenant-id: TENANTID
    config:
      profile: test
    kubernetes:
      discovery:
        enabled: true
        
name: test
environment: test
SetLocalEnvFlag: false

azure:
  application-insights:
    instrumentation-key: 
     
---

spring:
  config:
    activate:
      on-profile:
      - pcqtest
  sleuth: 
    enabled: true
  application:
      name:
  cloud:
    azure:
      keyvault:
        secret:
          property-sources[0]:
            credential:
              client-id: CLIENTID
              client-secret: CLIENTSECRET
            endpoint: https://acq-test-us-c-keyvault.vault.azure.net/
            profile:
              tenant-id: TENANTID 
    config:
      profile: pcqtest
    kubernetes:
      discovery:
        enabled: true
        
name: pcqtest
environment: pcqtest
SetLocalEnvFlag: false

azure:
  application-insights:
    instrumentation-key: 

---

spring:
  config:
    activate:
      on-profile:
      - stage
  application:
      name:
  cloud:
   azure:
      keyvault:
        secret:
          property-sources[0]:
            credential:
              client-id: CLIENTID
              client-secret: CLIENTSECRET
            endpoint: https://acq-stge-us-c-keyvault.vault.azure.net/
            profile:
              tenant-id: TENANTID
   config:
      profile: stage
   kubernetes: 
      discovery:
        enabled: true
name: stage
environment: stage
SetLocalEnvFlag: false

azure:
  application-insights:
    instrumentation-key: 
     
---

spring:
  config:
    activate:
      on-profile:
      - perf
  application:
      name: 
  cloud:
   azure:
      keyvault:
        secret:
          property-sources[0]:
            credential:
              client-id: CLIENTID
              client-secret: CLIENTSECRET
            endpoint: https://acq-perf-us-c-keyvault.vault.azure.net/
            profile:
              tenant-id: TENANTID
   config:
      profile: perf
   kubernetes: 
      discovery:
        enabled: true
name: perf
environment: perf
SetLocalEnvFlag: false

azure:
  application-insights:
    instrumentation-key: 
     
---

spring:
  config:
    activate:
      on-profile:
      - trng
  application:
      name: 
  cloud: 
   azure:
      keyvault:
        secret:
          property-sources[0]:
            credential:
              client-id: CLIENTID
              client-secret: CLIENTSECRET
            endpoint: https://acq-trng-us-c-keyvault.vault.azure.net/
            profile:
              tenant-id: TENANTID
   config:
      profile: trng
   kubernetes: 
      discovery:
        enabled: true
name: trng
environment: trng
SetLocalEnvFlag: false

azure:
  application-insights:
    instrumentation-key: 

---
#Please review while doing final prod configuration
spring:
  config:
    activate:
      on-profile:
      - prod
  application:
      name: 
  cloud: 
   azure:
      keyvault:
        secret:
          property-sources[0]:
            credential:
              client-id: CLIENTID
              client-secret: CLIENTSECRET
            endpoint: https://acq-prod-us-c-keyvault.vault.azure.net/
            profile:
              tenant-id: TENANTID
   config:
      profile: prod
   kubernetes: 
      discovery:
        enabled: true
name: prod
environment: prod
SetLocalEnvFlag: false

azure:
  application-insights:
    instrumentation-key: 
